"""
Objective: 

Connect to Vertex AI (Google Cloud AI platform): Learn how to establish a connection to Google's AI services using the Vertex AI SDK.
Load a pre-trained generative AI model -Gemini: Discover how to use a powerful, pre-trained AI model without building one from scratch.
Send image + text questions to the AI model: Understand how to provide input for the AI to process.
Extract text-based answers from the AI: Learn to handle and interpret the text responses generated by the AI model.
Understand the basics of building AI applications: Gain insights into the core concepts of integrating AI into software projects.
"""

from google import genai
from google.genai.types import HttpOptions, Part

client = genai.Client(http_options=HttpOptions(api_version="v1"))
response = client.models.generate_content(
    model="gemini-2.0-flash-001",
    contents=[
        "What is shown in this image?",
        Part.from_uri(
            file_uri="gs://cloud-samples-data/generative-ai/image/scones.jpg",
            mime_type="image/jpeg",
        ),
    ],
)
print(response.text)


"""
set env variables:
export GOOGLE_CLOUD_PROJECT='"project-id"'
export GOOGLE_CLOUD_LOCATION='"REGION"'
export GOOGLE_GENAI_USE_VERTEXAI=True
"""

#  code exceution
# /usr/bin/python3 /genai.py